sonar.projectKey=Diegomcha_AutoParte
sonar.organization=diegomcha

sonar.sources=.
sonar.tests=frontend/app/tests,backend/src/test/java

# Language specific settings
sonar.java.binaries=backend/target/classes
sonar.java.libraries=
sonar.java.test.binaries=backend/target/test-classes
sonar.java.test.libraries=
sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.eslint.reportPaths=frontend/eslint-report.json

sonar.python.version=3.11