sonar.projectKey=Diegomcha_AutoParte
sonar.organization=diegomcha

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Language specific settings
sonar.java.binaries=backend/target/classes
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.eslint.reportPaths=frontend/eslint-report.json
sonar.python.version=3.11