[project]
name = "autoparte-ocr"
requires-python = "~=3.11.0"
dependencies = [
    "fastapi~=0.141.1",
    "granian~=2.8.1",
    "mrz~=0.6.2",
    "python-multipart~=0.0.32",
    "rapidocr~=3.9.2",
    "opencv-python-headless~=5.0.0.93",
]
dynamic = ["version"]

[project.optional-dependencies]
deploy = ["uvloop~=0.22.1"]
cpu = ["onnxruntime~=1.28.0"]
gpu = ["onnxruntime-gpu~=1.28.0"]
dev = ["fastapi[standard]~=0.141.1", "pytest~=9.1.1", "pytest-cov~=7.1.0"]

[build-system]
requires = ["setuptools~=82.0.1", "setuptools_scm[simple]~=10.2.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
exclude-dependencies = ["opencv-python"]

[tool.setuptools_scm]
root = ".."
