spring.application.name=autoparte
#
spring.web.locale=es_ES
#
spring.mvc.apiversion.supported=1
spring.mvc.apiversion.required=true
spring.mvc.apiversion.use.path-segment=1
#
spring.data.web.pageable.serialization-mode=via_dto
#
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.mapping-resources=META-INF/orm.xml
spring.jpa.open-in-view=false
#
sentry.enabled=${SENTRY_ENABLED:true}
sentry.environment=${SENTRY_ENVIRONMENT:production}
sentry.dsn=${SENTRY_DSN:https://3c7724a17c8d639fcf752c9acd28e6d9@o4511343046426624.ingest.de.sentry.io/4511343047671888}
sentry.logs.enabled=true
sentry.traces-sample-rate=1.0
sentry.profile-session-sample-rate=1.0
sentry.profile-lifecycle=TRACE