# Development environment configuration
autoparte.ocr.url=http://localhost:6543
autoparte.ses.url=https://hospedajes.pre-ses.mir.es/hospedajes-web/ws/v1/comunicacion
autoparte.ses.initial-username=${SES_USERNAME}
autoparte.ses.initial-password=${SES_PASSWORD}
autoparte.ses.initial-landlord-code=${SES_LANDLORD_CODE}
# JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
# Cookie configuration
server.servlet.session.cookie.same-site=lax
# Expose Swagger UI and API docs in development
springdoc.swagger-ui.path=/api/docs/ui
springdoc.api-docs.path=/docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# Enable sentry in development mode & disable profiler to avoid errors in Windows machines
sentry.environment=development
sentry.profiles-sample-rate=0
# Enable SOAP message tracing for debugging
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE