autoparte.ocr-url=http://localhost:6543
#
spring.jpa.hibernate.ddl-auto=update
#
server.servlet.session.cookie.same-site=lax
#
springdoc.swagger-ui.path=/api/docs/ui
springdoc.api-docs.path=/docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
#
sentry.enabled=false
# TODO: remove this when security is implemented
spring.security.user.name=user
spring.security.user.password=$2a$12$xH5Qm5BsH5bnXYPcA5UX0uy2C6oOpqdSfTxcAaF8k9ak3MiQzoG22