name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-qube:
    name: SonarQube
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # CHECKOUT
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # V6.0.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      # SETUP
      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: frontend/package.json

      - name: Cache Bun dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.bun/install/cache
          key: bun-deps-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('frontend/bun.lock') }}

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          cache-dependency-path: backend/pom.xml

      # FRONTEND
      - name: (Frontend) Install dependencies
        working-directory: frontend
        run: bun ci --frozen-lockfile

      - name: (Frontend) Build
        working-directory: frontend
        run: bun run build

      - name: (Frontend) Run ESLint and generate report
        working-directory: frontend
        continue-on-error: true
        run: bun run lint:ci

      - name: (Frontend) Run tests and generate coverage
        working-directory: frontend
        continue-on-error: true
        run: bun run test --coverage

      # BACKEND
      - name: (Backend) Copy dependencies for SonarQube
        working-directory: backend
        run: mvn -B dependency:copy-dependencies

      - name: (Backend) Build
        working-directory: backend
        run: mvn -B compile

      - name: (Backend) Run tests and generate reports
        working-directory: backend
        continue-on-error: true
        run: mvn -B verify

      # SCAN
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # v8.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build images
    # needs: sonar-qube # TODO: Uncomment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./ocr
            dockerfile: ./ocr/docker/cpu.Dockerfile
            module: ocr
            suffix: cpu
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Extract container metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_${{ matrix.module }}
          flavor: |
            suffix=${{ matrix.suffix }},onlatest=true

      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_${{ matrix.module }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
